### ISSUE TITLE
Couldn't build source code in Lambda server

### ISSUE THREAD

**Issue by cactusxxx** [Fenton-Fenton-Fenton/alexa-tube#8]
Hi,
I have deployed the index.zip file to Lambda server, but when I click to Test button in Lambda server, there is following error:
{
  "errorMessage": "RequestId: 70874b4d-9f89-11e7-9593-3dd3d201fd52 Process exited before completing request"
}

The log is following:
START RequestId: 70874b4d-9f89-11e7-9593-3dd3d201fd52 Version: $LATEST
2017-09-22T11:30:32.116Z	70874b4d-9f89-11e7-9593-3dd3d201fd52	TypeError: Cannot read property 'type' of undefined
    at alextube.handle (/var/task/index.js:72:41)
    at exports.handler (/var/task/index.js:62:12)
END RequestId: 70874b4d-9f89-11e7-9593-3dd3d201fd52
REPORT RequestId: 70874b4d-9f89-11e7-9593-3dd3d201fd52	Duration: 43.23 ms	Billed Duration: 100 ms 	Memory Size: 384 MB	Max Memory Used: 52 MB	
RequestId: 70874b4d-9f89-11e7-9593-3dd3d201fd52 Process exited before completing request

Please help me to explain this,
Thank you

**Comment by Fenton-Fenton-Fenton** [comment]
Looks like you haven't set the timeout. This is why the skill is exiting before it has finished processing

**Comment by cactusxxx** [comment]
> Looks like you haven't set the timeout. This is why the skill is exiting before it has finished processing

I have set the timeout to 1 minutes in Configuration tab/Advanced settings as your instruction but the error is still occurred.

Thanks!

**Comment by Fenton-Fenton-Fenton** [comment]
Ah I see now that you are trying the test function within Lambda. You don't actually need to worry about this error - This because you are running the save and test option and haven't configured the test. If you want to make sure it isn't anything else then:- Next to the "test and save" button there is a "Actions" button, press this and select select Configure Test Event. Click on the Sample event template dropdown menu, scroll down and select "Alexa Start Session", then click "Save and Test". NOTE If you have setup the Application ID as per above then you will also need to paste this into the test code.

If it is successful then you should see this output:-

```
{
  "version": "1.11",
  "response": {
    "outputSpeech": {
      "type": "PlainText",
      "text": "Welcome to Google Search. What are you searching for?"
    },
    "shouldEndSession": false
  },
  "sessionAttributes": {}
}
```
This means that the basics of the skill are functioning.
